#!/bin/bash

echo "Reached /etc/sbin/fizzbuzz"

if [ -f /etc/sysconfig/fizzbuzz ]; then
   . /etc/sysconfig/fizzbuzz
else
  echo "Missing /etc/sysconfig/fizzbuzz"
fi

run_as_user()
{
    echo "Run $1 as (ajfaraday)"
    runuser -l ajfaraday $FIZZBUZZ_CMD $1 $2 $3 $4
    RETVAL=$?
    return $RETVAL
}

case $1 in
*)
  run_as_user $1